name: Run the Unit Tests

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
jobs:
  static-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP with Composer
      uses: php-actions/composer@v6
      with:
        php_version: 8.3

    - name: PHPStan static analysis
      run: |
        vendor/bin/phpstan --memory-limit=512M analyse

    - name: Run PHPUnit tests
      run: |
        vendor/bin/phpunit --process-isolation